import {readFile,readdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
export async function bundledNotices(inputs) {
  const packages = new Map();
  for(const file of Object.keys(inputs)) {
    if(!file.includes('node_modules/')) continue;
    let dir=dirname(resolve(file));
    while(!existsSync(dir+'/package.json') && dirname(dir)!==dir) dir=dirname(dir);
    const pkg=JSON.parse(await readFile(dir+'/package.json','utf8'));
    packages.set(pkg.name+'@'+pkg.version,{pkg,dir});
  }
  const sections=['Third-party notices\nGenerated by tools/notices.mjs from the bundled dependency inputs.\nManta code is MIT licensed; dependencies retain their respective licenses.\nUpstream source links below provide the corresponding unmodified library source.'];
  for(const [name,{pkg,dir}]of [...packages].sort(([a],[b])=>a.localeCompare(b))) {
    const repo=typeof pkg.repository==='string'?pkg.repository:pkg.repository?.url;
    const licenses=(await readdir(dir)).filter(file=>/^(licen[sc]e|copying|notice)([._-].*)?$/i.test(file)).sort();
    sections.push(`${name}\nLicense: ${typeof pkg.license==='string'?pkg.license:JSON.stringify(pkg.license||pkg.licenses)}\nSource: ${repo||pkg.homepage||'https://www.npmjs.com/package/'+pkg.name}\n`+(await Promise.all(licenses.map(file=>readFile(dir+'/'+file,'utf8')))).join('\n'));
  }
  return sections.join('\n\n'+'='.repeat(72)+'\n\n')+'\n';
}
