// A display family describes a structure. Domain-specific names remain input aliases.
export const aliases = {
  'it-state':'architecture','high-level':'architecture','deployment':'architecture',
  dependency:'architecture','data-flow':'architecture','dp-integration':'architecture',
  process:'flowchart',medallion:'flowchart','org-chart':'tree','db-schema':'er',
};
export const canonicalType = name => aliases[name] || name;
export const families = [
  ['architecture','구성도','구성요소의 경계와 연결'],
  ['er','ER / DB 모델','테이블의 필드와 관계'],
  ['uml-class','UML 클래스','클래스의 멤버와 타입 관계'],
  ['nested','중첩 범위','어느 범위가 어느 범위를 포함하는가'],
  ['dp-security-matrix','권한 표','역할별 리소스 접근 관계'],
  ['sankey','Sankey','양이 어떻게 나뉘고 합쳐지는가'],
  ['flowchart','흐름도','처리 순서와 조건 분기'],
  ['tree','트리','부모와 자식 관계'],
  ['sequence','시퀀스','참여자 사이의 호출 순서'],
  ['state','상태 전이','상태가 바뀌는 조건'],
  ['swimlane','스윔레인','담당별 처리 순서'],
  ['kanban','칸반','상태별 작업 카드'],
  ['story-map','스토리맵','활동과 릴리스별 작업'],
  ['fishbone','원인 분석','원인과 분류가 하나의 결과로 이어지는 관계'],
  ['loop','순환','반복되는 단계와 중심'],
  ['layers','계층 스택','위아래 계층의 의존 순서'],
  ['pyramid','피라미드','상위 단계와 기반 단계'],
  ['venn','벤','집합의 교집합'],
  ['block','블록 격자','명시한 칸과 크기에 따른 배치'],
  ['wardley','Wardley 지도','사용자와의 거리와 구성요소의 성숙도'],
  ['timeline','타임라인','시간에 따른 사건'],
  ['gantt','간트','작업의 기간과 겹침'],
  ['journey','사용자 여정','단계별 경험과 참여자'],
  ['bar','막대','항목별 수치 비교'],
  ['line','선','연속된 값의 변화'],
  ['scatter','산점도','두 수치의 관계'],
  ['waterfall','워터폴','증감이 합계에 미치는 영향'],
  ['radar','레이더','여러 축에서 수열 비교'],
  ['polar','극좌표','방향별 크기 비교'],
  ['quadrant','사분면','두 기준에 따른 위치'],
  ['treemap','트리맵','계층별 비중'],
].map(([id,label,purpose])=>({id,label,purpose}));
